### ISSUE TITLE
Provide <Fabric /> component's functionality as a utility

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#10]
Fabric expects us to wrap our app in a <Fabric /> component. This component adds font styles for the rest of the app, and will eventually handle language-specific fonts for us. We cannot wrap Yammer.com in a <Fabric /> component since most of Yammer is not React.

Fabric engineers recognize this issue and recommend we contribute to office-ui-fabric-react by extracting the <Fabric /> component's functionality into a utility module. This utility module would allow us to provide an HTML element and would keep its list of CSS classes (and associated glamor styles) up to date as they change.

This does not block development as our Storybook app will wrap its stories in a <Fabric /> component, but this does block us from integrating with YamJS.

**Comment by dzearing** [comment]
Please do this in fabric :)

**Comment by swese44** [comment]
closing this out as we no longer need the functionality for Yammer, and Fabric will no longer require the `<Fabric>` wrapper
