### ISSUE TITLE
Simplify component examples, separate visual-diff-only examples

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#116]
It's a little hard to read the docs as many components have several and/or complicated examples. We should move anything that's only for visual diffs to a new section. Proposal:

Sections:
- **Intro.** How to consume YamUI in your app
- **Components.** Simple, clear docs on what a component does, what it should or shouldn't be used for, and simple examples for relevant props. Maybe in the future break them up into categories (layout, forms, interactive components) but not necessary at the moment.
- **Demos.** Examples of common component compositions - hovercards, button action bars, etc.
- **Visual tests.** These are really only there for visual tests and shouldn't be clogging up the component docs. Would be nice to keep these near their respective components though, maybe use a naming convention like ComponentName.visual.md?

and continue visual-diffing all examples

**Comment by unindented** [comment]
Sounds good to me.

**Comment by unindented** [comment]
There's going to be some a lot of redundancy most of the time between normal examples and examples for visual tests though.

**Comment by unindented** [comment]
Why not just simplify the examples, but keep visual-diffing those? We'll probably want to document examples for all important use cases anyways.

**Comment by swese44** [comment]
ah yes that's what i meant, wasn't very clear. still visual-diff all examples, just separate the oddballs and complex examples out of the primary component documentation

**Comment by chrismohr** [comment]
Looks like this was mostly done.  Feel free to reopen if you want to keep rolling with any of these ideas.
