### ISSUE TITLE
Persona shows flash of color/initials even when passing image to Avatar

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#12]
For example, if it's a deleted group, you might see a color flash before it displays the no_photo icon. I only mention this example because it's bright and then dull and so it stands out. Someone might think it's a peek at a deleted group image -- they see content that is quickly replaced

**Comment by swese44** [comment]
@richardtagger did you already resolve this?

**Comment by chrismohr** [comment]
Looking at https://microsoft.github.io/YamUI/#!/Avatar/7 with 6x cpu throttling, and I'm not seeing the issue.  Feel free to reopen with repro steps if it's still a problem.
