### ISSUE TITLE
Module: PreviewCard

### ISSUE THREAD

**Issue by adrianmg** [Microsoft/YamUI#138]
Ready to go to start implementation.

Make sure to ping me or Manuel to make a review before starting to implement anything so we can tackle issues, questions, and doubts in advance.

http://zpl.io/Vq1Ne3Z

**Comment by swese44** [comment]
i have a PR in progress so removing other assignees

**Comment by chrismohr** [comment]
Done https://microsoft.github.io/YamUI/#previewcard
