### ISSUE TITLE
Textfield Error has the wrong border color on hover when focused

### ISSUE THREAD

**Issue by adrianmg** [Microsoft/YamUI#200]
Textfields border is red when it's an error state. When the textfield gets the focus we change the border color to blue. For some reason we're not keeping the blue border color when hovering the input on the error state.

Could we fix it, please? @unindented @swese44 

![bug mov](https://user-images.githubusercontent.com/589285/34798071-719ac47c-f60f-11e7-810b-334b71b6d974.gif)

**Comment by unindented** [comment]
I think @chrismohr has the most context on this component.

**Comment by chrismohr** [comment]
@adrianmg It looks like this is no longer reproducing. The border color stays red on focus and hover. I suspect we got the fix for free from fabric. Can you confirm that this is as desired, and close?
