### ISSUE TITLE
Provide a container query solution for responsive components

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#216]
[react-container-query](https://github.com/d6u/react-container-query) could be the best solution, but it weighs in at 42kb. we could contribute to lighten this footprint by replacing lodash.isequal with something tiny to compare objects, and possibly update the resize-observer-lite dependency:
https://github.com/d6u/react-container-query/issues/66

**Comment by unindented** [comment]
How does [`react-media`](https://github.com/ReactTraining/react-media) compare?

**Comment by swese44** [comment]
`react-media` is great for media queries, but that's at the page-level. container queries will let individual components be responsive based on their parent container's width.

i've also started a thread in the Fabric group on Teams, i'll tag you on it

**Comment by swese44** [comment]
`react-media` might make more sense for an app to manage than YamUI since it's dealing with page-level media queries / layouts. if YamUI introduces an individual component which is responsive at the container-level we can figure out a container-query solution

**Comment by swese44** [comment]
`react-container-query` has removed lodash from their dependency tree. including the library now adds 24kb of minified JS

**Comment by swese44** [comment]
pending: https://github.com/d6u/react-container-query/issues/71

**Comment by chrismohr** [comment]
Resolved by https://github.com/Microsoft/YamUI/pull/443
