### ISSUE TITLE
Textfield Underlined Bugs

### ISSUE THREAD

**Issue by adrianmg** [Microsoft/YamUI#219]
I've spotted a few bugs when revisiting Textfield Underlined. Since we're also going to use them in Search Box we should fix them and make sure both components are working correctly.

- Font-size and height are wrong compared to design spec (check attachment)
- On Error case, the error hint is 1px vertically misaligned
- There is no focus case, when the input is active it should have the focus state (blue line)
- Make sure that focus case remains red when the error is active too (as it happens on base textfield)

Let me know if something is not clear enough!

![image](https://user-images.githubusercontent.com/589285/35251893-751a94a6-ff92-11e7-9a26-e7f07ad6e5c6.png)

**Comment by swese44** [comment]
i'm taking care of the height issue with PreviewCard, it's already a big PR so i won't address the other bugs in it. let's file individual bugs as individual issues so we can track them easier
