### ISSUE TITLE
Rename badge icons

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#263]
These are probalby tied a bit too close to Yammer business logic, can we rename them to reflect their content rather than the intended user on Yammer.com?

I think just the 3 badge icons:
- BadgeAdmin - This uses FavoriteStar, how about CircleFavoriteStar?
- BadgeFlexternal - This uses Globe, how about CircleGlobe?
- BadgeNew - This looks like it uses Fabric's Emoji2 icon, maybe CircleEmoji2? not sure about this one

**Comment by richardtagger** [comment]
in Fabric land does 'coin' mean 'circle'?

**Comment by BrendanMcK** [comment]
In FabricLand, Coin is the (usually-)circular avatar/image part of a Persona - Persona being the image plus the accompanying text. Example from https://developer.microsoft.com/en-us/fabric#/components/persona 

![image](https://user-images.githubusercontent.com/1754373/36820855-df3df132-1ca4-11e8-9725-4fc959b087b4.png)

**Comment by adrianmg** [comment]
I can't find anything with coin on Fabric icon set though

![image](https://user-images.githubusercontent.com/589285/36820866-ed048cb8-1ca4-11e8-8475-b0194f76e540.png)

**Comment by BrendanMcK** [comment]
Name nit-picking: I'd suggest CircleStar, CircleGlobe, CircleFace or similar - sticking with describing the shape. 'Favorite' implies policy as much as 'Admin' does, while Emoji2 is an impl detail.

**Comment by adrianmg** [comment]
I'm taking a look at other icons and we're using 'circle' extensively. Also, we're mixing different approaches: some icons have the action as the name and others are more focused on the shape.

Until now, we've been literally respecting the original Fabric Iconography naming to avoid duplicates and confusion as much as possible (we're copying/forking their icon most of the time).

**Comment by adrianmg** [comment]
Updated names for badge icons to:

- CircleFavoriteStar
- CircleGlobe
- CircleEmoji2
