### ISSUE TITLE
Add "type" prop for button

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#7]
const ButtonType = 'button' | 'submit' | 'reset';
Should default to "button".

**Comment by unindented** [comment]
Fabric doesn't support this, right? I don't see any issues open in their repo. Should we open one?

**Comment by swese44** [comment]
@unindented Fabric also accepts HTML attribute props, so you could pass in type or other `<button>` attributes and it should pass them along to the DOM

**Comment by swese44** [comment]
(i have not verified this specific case, but it should work)
