### ISSUE TITLE
Styleguide shows children prop for components which don't support it

### ISSUE THREAD

**Issue by swese44** [Microsoft/YamUI#93]
`react-styleguidist` or `react-docgen-typescript` seems to be adding "children" to props if it doesn't exist. Our nestable components show the comments on our children prop, but our leaf node components show an empty description.

**Comment by unindented** [comment]
Could it be because it's a prop that all React components have?

**Comment by chrismohr** [comment]
Looks like this may have been fixed with an update. I don't see a `children` prop on Avatar or Button, but I am on Block, and it shows the description.
